# -*- coding: utf-8 -*-
"""Another copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIJ25QH9IDADGRmuxD09yTH35uveHi3O
"""



!pip install streamlit

!streamlit --version

import streamlit as st
from transformers import pipeline

# Initialize the custom GPT model (Replace with your actual model)
@st.cache_resource
def load_gpt():
    # Example: Using Hugging Face pipeline (replace with your custom model)
    return pipeline("text-generation", model="gpt2")

gpt_model = load_gpt()

# Page Configuration
st.set_page_config(page_title="Custom GPT", page_icon="🤖", layout="wide")

# Title and Description
st.title("Custom GPT Job Search Assistant")
st.write("""
This is your personal job search assistant powered by a custom GPT.
Enter a query related to your job search, and the assistant will generate a response.
""")

# Sidebar for additional options
with st.sidebar:
    st.header("Options")
    max_length = st.slider("Max Response Length", min_value=50, max_value=500, value=150)
    temperature = st.slider("Creativity Level (Temperature)", min_value=0.1, max_value=1.0, value=0.7)
    top_k = st.slider("Top-k Sampling", min_value=1, max_value=50, value=10)

# Input Section
user_input = st.text_area("Enter your query:", placeholder="E.g., 'Suggest IT jobs for fresh graduates in New York'")

# Generate Button
if st.button("Generate Response"):
    if user_input.strip():
        with st.spinner("Generating response..."):
            response = gpt_model(
                user_input,
                max_length=max_length,
                temperature=temperature,
                top_k=top_k,
                num_return_sequences=1,
            )[0]['generated_text']
            st.success("Response Generated!")
            st.markdown("### Response:")
            st.write(response)
    else:
        st.warning("Please enter a query to generate a response.")

# Footer
st.markdown("---")
st.markdown("**Custom GPT App** | Powered by AI | Created with ❤️ using Streamlit")